Joy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('v3.urls')),    

]

v1/urls.py
from django.urls import path
from .views import *

app_name = 'v1'
urlpatterns = [
    path('', index, name='index'),
    path('redirect', index_redirect, name='index_redirect'),
    path('json', index_json, name='index_json'),
    path('file', index_file, name='index_file'),
]

v2/urls.py
from django.urls import path
from .views import *

app_name = 'v2'
urlpatterns = [
    path('', index, name='index'),
    path('name', name, name='name'),
    path('name/<str:keyword>', username, name='username'),
]

v3/urls.py
from django.urls import path
from .views import *

app_name = 'v3'
urlpatterns = [
    path('', index, name='index'),
]

v4/urls.py
from django.urls import path
from .views import *

app_name = 'v4'
urlpatterns = [
    # path('', index, name='index'),
    path('', BaseView.as_view()),
    path('index', IndexView.as_view(), name='index'),
    path('html', HtmlView.as_view(), name='html'),
    path('name/<str:name>', NameView.as_view(), name='name'),
]

v5/urls.py
from django.urls import path
from .views import *

app_name = 'v5'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('result', ResultView.as_view(), name='result'),
    path('basic_form', BasicFormView.as_view(), name='basic_form'),
    path('done', DoneView.as_view(), name='done'),
]

v1/models.py
from django.db import models

# Create your models here.

v2/models.py
from django.db import models

# Create your models here.

v3/models.py
from django.db import models

# Create your models here.

v4/models.py
from django.db import models

# Create your models here.

v5/models.py
from django.db import models

# Create your models here.

v5/forms.py
from django import forms


def validator_min_length(value):
    if len(value) < 3:
        raise forms.ValidationError('최소 글자는 3자 입니다.')


class MyForm(forms.Form):
    name = forms.CharField(max_length=10)
    hobby = forms.CharField(help_text="취미를 입력해주세요.", validators=[validator_min_length])

v1/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, FileResponse


# Create your views here.
def index(request):
    response = HttpResponse()
    response.write("<h1>Welcome</h1>")
    response.write("<p>This is my first Django. </p>")
    return response


def index_redirect(request):
    return HttpResponseRedirect('http://google.com')


def index_json(request):
    return JsonResponse({'key': 'value'})


def index_file(request):
    img = open('./images/IU_MelOn_Music_Awards_2017_06.jpg', 'rb')
    response = FileResponse(img)
    return response










# from django.shortcuts import render

v2/views.py
# Create your views here.
from django.shortcuts import render


def index(request):
    return render(request, 'v2/index.html')


def name(request):
    return render(request, 'v2/name.html', {'name':'Joy'})


def username(request, keyword):
    return render(request, 'v2/name.html', {'name':keyword})

v3/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'v3/index.html')

v4/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

# v1 버전에서 만든 것
# def index(request):
#     response = HttpResponse()
#     response.write("<h1>Welcome</h1>")
#     response.write("<p>This is my first Django. </p>")
#     return response

# 실제로는 request.method 를 통해 HTTP 방식에 따라 처리를 해준다.
# 이 예시는 함수형 뷰
# def index(request):
#     if request.method == 'GET':
#         response = HttpResponse()
#         response.write("<h1>Welcome</h1>")
#         response.write("<p>This is my first Django. </p>")
#         return response

# 이것을 클래스형 뷰로 변경한 것
class BaseView(View):
    def get(self, request, *args, **kwargs):
        response = HttpResponse()
        response.write("<h1>Welcome</h1>")
        response.write("<p>This is my first Django. </p>")
        return response


class IndexView(View):
    template_name = "v2/index.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class HtmlView(TemplateView):
    template_name = "v3/index.html"


@method_decorator(csrf_exempt, name='dispatch')
class NameView(TemplateView):
    template_name = "v2/name.html"

    def get_context_data(self, **kwargs):
        context = super(NameView, self).get_context_data(**kwargs)
        return context

    def get(self, request, *args, **kwargs):
        """
        GET 방식으로 요청이 들어오면 URL에 입력된 값을 context에 담아 template_name에 해당되는 html을 렌더링하도록 처리한다.
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, **kwargs):
        """
        POST 방식으로 들어오면 body의 내용을 context에 담아 template_name에 해당되는 html을 렌더링하도록 처리한다.
        :param request:
        :param kwargs:
        :return:
        """
        context = self.get_context_data(**kwargs)
        try:
            body = json.loads(request.body.decode('utf8'))
            context['name'] = body['keyword']
        except:
            pass
        return self.render_to_response(context)

v5/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from django.views.generic import TemplateView, FormView

from v5.forms import MyForm


class IndexView(TemplateView):
    template_name = "v5/index.html"


class ResultView(View):
    template_name = "v5/result.html"

    def post(self, request, *args, **kwargs):
        result = {
            'name': request.POST['name'],
            'hobby': request.POST['hobby'],
        }
        return render(request, self.template_name, result)


class BasicFormView(FormView):
    template_name = 'v5/basic_form.html'
    form_class = MyForm
    success_url = 'done'

    def form_valid(self, form):
        return super().form_valid(form)


class DoneView(TemplateView):
    template_name = "v5/done.html"

templates/v2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Tutorial v2</title>
</head>
<body>
<h2>Hello</h2>
May the force be With you!
</body>
</html>

templates/v2/name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Tutorial v2</title>
</head>
<body>
<h2>Hello {{name}}</h2>
May the force be With you!
</body>
</html>

templates/v3/index.html
<!DOCTYPE html>
<html lang="ko-KR">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% load static %}
        <title>Monthly Project 1</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top">Daisy's Time Series Analysis</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Description</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">EuStockMarkets EDA </h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5"> Programmers AI dev course 4th <p>
                        <p class="text-white-75 mb-5">- B반 이지윤 -</p>
                        <a class="btn btn-primary btn-xl" href="#about">Find Out More</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">Time series analysis about EuStockMarkets</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">You can downroad 'EuStockMarkets.csv' file by clicking the button below.</p>
                        <a class="btn btn-light btn-xl" href="https://r-data.pmagunia.com/dataset/eustockmarkets">Click here</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container px-4 px-lg-5">
                <h2 class="text-center mt-0">Description</h2>
                <hr class="divider" />
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">Required Library</h3>
                            <p class="text-muted mb-0">numpy, pandas, pyplot, seaborn</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">About Plot</h3>
                            <p class="text-muted mb-0">4가지 정보를 하나로 표현한 그래프와 y label에 따라 <br>4가지로 표현한 그래프입니다.</br></p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-globe fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">About Histogram</h3>
                            <p class="text-muted mb-0">어떠한 변화도 가하지 않은 히스토그램과 차분에 대한 히스토그램으로,
                            추세를 제거하기 위해 시간 상 인접한 데이터의 차이를 구하면 정규분포를 따르는 형태로 변화합니다.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <div class="mb-2"><i class="bi-heart fs-1 text-primary"></i></div>
                            <h3 class="h4 mb-2">About Scatter</h3>
                            <p class="text-muted mb-0">시간에 따른 서로 다른 두 주식의 가치를 단순 산점도를 그리면 거의 1과 가깝습니다.
                                <br>허위여부를 보기 위해 차분(diff)에 대한 두 주식의 일일 가치 변동에
                                shift 함수를 적용한 산점도는 두 주가의 상관관계가 사라져 한 변수로 다른 변수를 예측하지 못합니다.</br></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Portfolio-->
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'assets/img/portfolio/fullsize/EuStockMarkets_plot.png' %}" title="EDA result 1">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/EuStockMarkets_plot.png' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">EDA result 1</div>
                                <div class="project-name">EuStockMarkets basic plot</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'assets/img/portfolio/fullsize/EuStockMarkets_basic_hist.png' %}" title="EDA result 2">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/EuStockMarkets_basic_hist.png' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">EDA result 2</div>
                                <div class="project-name">EuStockMarkets basic histogram</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'assets/img/portfolio/fullsize/EuStockMarkets_basic_scatter.png' %}" title="EDA result 3">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/EuStockMarkets_basic_scatter.png' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">EDA result 3</div>
                                <div class="project-name">EuStockMarkets basic scatter</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'assets/img/portfolio/fullsize/EuStockMarkets_plots.png' %}" title="EDA result 4">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/EuStockMarkets_plots.png' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">EDA result 4</div>
                                <div class="project-name">EuStockMarkets 4 plots</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'assets/img/portfolio/fullsize/EuStockMarkets_diff_hist.png' %}" title="EDA result 5">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/EuStockMarkets_diff_hist.png' %}" alt="..." />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">EDA result 5</div>
                                <div class="project-name">EuStockMarkets diff histogram</div>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% static 'assets/img/portfolio/fullsize/EuStockMarkets shift scatter.png' %}" title="EDA result 6">
                            <img class="img-fluid" src="{% static 'assets/img/portfolio/thumbnails/EuStockMarkets shift scatter.png' %}" alt="..." />
                            <div class="portfolio-box-caption p-3">
                                <div class="project-category text-white-50">EDA result 6</div>
                                <div class="project-name">EuStockMarkets shift scatter</div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Call to action-->
        <section class="page-section bg-dark text-white">
            <div class="container px-4 px-lg-5 text-center">
                <h2 class="mb-4">If you want to contact me, please click the icons.</h2>
                <br>
                <a class="btn btn-light btn-xl" href="https://github.com/BBARRY-Lee/">GitHub</a>&nbsp; &nbsp;
                <a class="btn btn-light btn-xl" href="https://bbarry-meow.tistory.com/">Tistory Blog</a>&nbsp; &nbsp;
                <a class="btn btn-light btn-xl" href="mailto:bbarry.official@gmail.com">E-Mail</a>
            </div>
                <br><br>
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-4 text-center mb-5 mb-lg-0">
                        <i class="bi-phone fs-2 mb-3 text-muted"></i>
                        <div>+82 010-4922-2066</div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2022 - Jiyun Lee</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/v5/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Tutorial</title>
</head>
<body>
<div id="wrapper">
장고 5번째 튜토리얼 - Form
</div>
<div>

    {% block question %}
    {% endblock question %}

    {% block result %}
    {% endblock result %}

</div>
</body>
</html>

templates/v5/basic_form.html
{% extends "v5/base.html" %}

{% block question %}
    <p>
        Basic Form 정보를 입력해 보세요!
    </p>

    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">OK</button>
        </form>
   </div>

{% endblock question %}

templates/v5/done.html
{% extends "v5/base.html" %}

{% block question %}
    <p>
        정보가 입력되었습니다.
    </p>

    <p>
        <a href="{% url 'v5:basic_form' %}">돌아가기</a>
    </p>

{% endblock question %}

templates/v5/index.html
{% extends "v5/base.html" %}

{% block question %}
    <p>
        정보를 입력해 보세요!
    </p>
    <form action="{% url 'v5:result' %}" method="POST">
        {% csrf_token %}
        <p>
            <label for="name">이름: </label>
            <input id="name" type="text" name="name">
        </p>
        <p>
            <label for="hobby">취미: </label>
            <input id="hobby" type="text" name="hobby">
        </p>
        <input type="submit" value="OK">
    </form>

{% endblock question %}

templates/v5/result.html
{% extends "v5/base.html" %}

{% block result %}
    <p>
        입력 결과는 아래와 같습니다.
    </p>
    <li>이름 : {{ name }}</li>
    <li>취미 : {{ hobby }}</li>
    <p>
        <a href="{% url 'v5:index' %}">돌아가기</a>
    </p>

{% endblock result %}